// USERS

GET http://localhost:4000/api/users

###

POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "username": "user",
    "password": "1234",
    "avatar": "avatar1"
}

###

POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "username": "user",
    "password": "1234"
}

###

POST http://localhost:4000/api/users/logout

###

PUT http://localhost:4000/api/users/
Content-Type: application/json

{
    "_id": "6081a9c17240e25abcf17839",
    "access": "admin"
}

###

DELETE http://localhost:4000/api/users/6081a9c17240e25abcf17839

###


// POSTS

GET http://localhost:4000/api/posts

###

POST http://localhost:4000/api/posts
Content-Type: application/json

{
    "message": "Jag vill ha godis!"
}

###
PUT http://localhost:4000/api/posts/
Content-Type: application/json

{
    "id": "60afb9fae76eac17c857e0c8",
    "message": "Ge mig godis nu!!!"
}

###

DELETE http://localhost:4000/api/posts/60afb9fae76eac17c857e0c8

###