GET http://localhost:4000/api/posts

###

POST http://localhost:4000/api/posts
Content-Type: application/json

{
    "user": "Ruben",
    "message": "Jag vill ha ärtplättar!!!!",
    "timestamp": "2021-04-22"
}

