// USERS

GET http://localhost:4000/api/users

###
POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "username": "admin",
    "password": "1234",
    "access": "admin"
}

###
POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "username": "test2",
    "password": "1234",
    "access": "user",
    "avatar": "avatar1"
}

###

POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "username": "Randomuser",
    "password": "abc"
}

###

POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "username": "test2",
    "password": "1234"
}

###

POST http://localhost:4000/api/users/logout

###

PUT http://localhost:4000/api/users/
Content-Type: application/json

{
    "_id": "6081bbdd153b602dc09e1ad3",
    "access": "admin"
}

###

DELETE http://localhost:4000/api/users/60a75fe1b8f03618ec9e0f4b

###

GET http://localhost:4000/api/users/authenticate
Content-Type: application/json

###

// POSTS

GET http://localhost:4000/api/posts

###

POST http://localhost:4000/api/posts
Content-Type: application/json

{
    "user": "Tony",
    "avatar": "avatar1",
    "message": "Jag vill ha nya gitarrer och mer kaffe!!!!!"
}

###

PUT http://localhost:4000/api/posts/
Content-Type: application/json

{
    "_id": "60aa705eb894e63328d689ef",
    "user": "test2",
    "message": "hejhej!!!"
}

###
PUT http://localhost:4000/api/posts/
Content-Type: application/json

{
    "_id": "6089dd1a3bb7b716f0ad26e7",
    "user": "Ruben",
    "message": "Ge mig godis!!!"
}

###

DELETE http://localhost:4000/api/posts/60a7726fd292d018f8146881
Content-Type: application/json
{
"_id": "60a7726fd292d018f8146881",
  "user": "Tony",
  "message": "Jag vill ha nya gitarrer och mer kaffe!!!!!"
}

###